CREATE DATABASE respaldo_db_test;

USE respaldo_db_test;

/*VERIFICAR EL TOTAL DE TABLA EN MI BASE DE DATOS*/
SHOW TABLES;
/*VERIFICAR EL TOTAL DE TRIGGERS EN MI BASE DE DATOS*/
SHOW TRIGGERS FROM respaldo_db_test;
/*CONSULTAR LOS REGISTROS DE LOS USUARIOS*/
SELECT * FROM tb_users;
/*CONSULTAR LOS REGISTROS DE LA BITACORA*/
SELECT * FROM tb_logs;

/*VERIFICA LOS USUARIOS REMOTOS CREADOS EN EL SERVIDOR */
SELECT user,host FROM mysql.user WHERE host="%";

/*VERIFICAR LOS ROLES ASIGNADOS A LOS USUARIOS REMOTOS CREADOS EN EL SERVIDOR*/
SELECT
    FROM_USER AS Rol,
    FROM_HOST AS Host_Rol,
    TO_USER AS Usuario,
    TO_HOST AS Host_Usuario
FROM mysql.role_edges
ORDER BY FROM_USER, TO_USER;